### ISSUE TITLE
Scary use of exec

### ISSUE THREAD

**Issue by ghost** [dimag0g/hwfarm#1]
It's possible to insert commands by simply renaming a board
For example, board=";ls;"
```
[REDACTED]
```
board=";ls /home;"
```
pi
```
board=";ls /home/pi;"
```
[REDACTED]
```
![image](https://user-images.githubusercontent.com/17634568/100182636-fb5c3280-2ed4-11eb-8d7c-819e9deba738.png)
![image](https://user-images.githubusercontent.com/17634568/100182869-82a9a600-2ed5-11eb-94bd-a2b51a3735db.png)

**Comment by dimag0g** [comment]
That's indeed scary, thanks for reporting. I somehow forgot that everything coming from $_POST is user input, not just things for which there are forms.

I've already fixed it on my server, will do more testing before pushing anything to the repo.

**Comment by dimag0g** [comment]
I hope I got all of it with https://github.com/dimag0g/hwfarm/commit/e13bb8fbe55b94bc856fc8bf503337b2e939990d
